//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronicleOnline.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChronicleOnline.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Your Holiday Here.
        /// </summary>
        internal static string BookHolidayPage_Message {
            get {
                return ResourceManager.GetString("BookHolidayPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string Brand_Accent {
            get {
                return ResourceManager.GetString("Brand_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chronicle.
        /// </summary>
        internal static string Brand_Primary {
            get {
                return ResourceManager.GetString("Brand_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Common_Refresh {
            get {
                return ResourceManager.GetString("Common_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Fire Report Page.
        /// </summary>
        internal static string FireReportPage_Message {
            get {
                return ResourceManager.GetString("FireReportPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Holiday Page.
        /// </summary>
        internal static string HolidayPage_Message {
            get {
                return ResourceManager.GetString("HolidayPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Home Page.
        /// </summary>
        internal static string HomePage_Message {
            get {
                return ResourceManager.GetString("HomePage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records for this date..
        /// </summary>
        internal static string LiveStatus_NoRecords {
            get {
                return ResourceManager.GetString("LiveStatus_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Status.
        /// </summary>
        internal static string LiveStatus_Title {
            get {
                return ResourceManager.GetString("LiveStatus_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Holiday/Sick/Absence.
        /// </summary>
        internal static string Nav_BookHoliday {
            get {
                return ResourceManager.GetString("Nav_BookHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Report.
        /// </summary>
        internal static string Nav_FireReport {
            get {
                return ResourceManager.GetString("Nav_FireReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        internal static string Nav_Holiday {
            get {
                return ResourceManager.GetString("Nav_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Nav_Language {
            get {
                return ResourceManager.GetString("Nav_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Status.
        /// </summary>
        internal static string Nav_LiveStatus {
            get {
                return ResourceManager.GetString("Nav_LiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime.
        /// </summary>
        internal static string Nav_Overtime {
            get {
                return ResourceManager.GetString("Nav_Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TA Fire Reporting.
        /// </summary>
        internal static string Nav_TaFireReporting {
            get {
                return ResourceManager.GetString("Nav_TaFireReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Shows Your Overtime Status.
        /// </summary>
        internal static string OvertimePage_Message {
            get {
                return ResourceManager.GetString("OvertimePage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChronicleOnline.
        /// </summary>
        internal static string Shell_AppTitle {
            get {
                return ResourceManager.GetString("Shell_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clocked In.
        /// </summary>
        internal static string Status_ClockedIn {
            get {
                return ResourceManager.GetString("Status_ClockedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string Status_Exception {
            get {
                return ResourceManager.GetString("Status_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Clocked In.
        /// </summary>
        internal static string Status_NotClockedIn {
            get {
                return ResourceManager.GetString("Status_NotClockedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Not Found.
        /// </summary>
        internal static string Status_PersonNotFound {
            get {
                return ResourceManager.GetString("Status_PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ta Who Are Fire Are Shown Here.
        /// </summary>
        internal static string TaFireReportingPage_Message {
            get {
                return ResourceManager.GetString("TaFireReportingPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Word_All {
            get {
                return ResourceManager.GetString("Word_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        internal static string Word_Tags {
            get {
                return ResourceManager.GetString("Word_Tags", resourceCulture);
            }
        }
    }
}
